font_family      Nimbus Mono PS
font_size        14.0

# Cursor
cursor_shape          beam
cursor_blink_interval 0.5

# Scrollback
scrollback_lines 10000

# Window
window_padding_width 6
hide_window_decorations yes
confirm_os_window_close 0

# Tabs
tab_bar_edge       bottom
tab_bar_style      powerline
tab_powerline_style slanted

# Bell
enable_audio_bell no

# Allow Wayland clipboard integration via OSC 52
clipboard_control write-clipboard write-primary read-clipboard read-primary

# Modus Vivendi
active_tab_foreground #44bc44                                                                                      
active_tab_background #1e1e1e                                                                                      
inactive_tab_foreground #989898                                                                                    
inactive_tab_background #000000                                                                                    
                                                                                                                   
foreground #ffffff                                                                                                 
background #000000                                                                                                 
selection_foreground #000000                                                                                       
selection_background #ffffff                                                                                       
                                                                                                                   
color0 #000000                                                                                                     
color1 #ff5f59                                                                                                     
color2 #44bc44                                                                                                     
color3 #d0bc00                                                                                                     
color4 #2fafff                                                                                                     
color5 #feacd0                                                                                                     
color6 #00d3d0                                                                                                     
color7 #989898                                                                                                     
color8 #1e1e1e                                                                                                     
color9 #ff6b55                                                                                                     
color10 #70b900                                                                                                    
color11 #dfaf7a                                                                                                    
color12 #79a8ff                                                                                                    
color13 #b6a0ff                                                                                                    
color14 #6ae4b9                                                                                                    
color15 #ffffff