general {
    disable_loading_bar = true
    grace = 3
    hide_cursor = true
}

background {
    color = rgb(0, 0, 0)
}

input-field {
    size = 240, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgb(26, 26, 26)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(230, 230, 230)
    placeholder_text = password
    placeholder_text_color = rgb(153, 153, 153)
    fade_on_empty = false
    position = 0, -80
    halign = center
    valign = center
}

label {
  text = cmd[update:1000] date '+%H · %M'
  color = rgba(230,230,230,1)
  font_size = 58
  font_family = Space Mono
  position = 0, 100
  halign = center
  valign = center
}