# Test wallpaper should be bundled in hypr dir
# Wallpaper courtesy of engin akyurt (https://unsplash.com/@enginakyurt)
# License: https://unsplash.com/license
# Monitor needs to be changed. Does not work in a virtual machine without 3D accel.

wallpaper {
    monitor = eDP-1 
    path = $HOME/.config/hypr/blue.jpg
    fit_mode = cover
}
